#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/oplus/camera/camera

PRODUCT_COPY_FILES += \
    vendor/oplus/camera/camera/proprietary/odm/etc/camera/license_release_fdc.lic:$(TARGET_COPY_OUT_ODM)/etc/camera/license_release_fdc.lic \
    vendor/oplus/camera/camera/proprietary/odm/etc/camera/livephoto_coverenhancer/models/license_release_gallery.lic:$(TARGET_COPY_OUT_ODM)/etc/camera/livephoto_coverenhancer/models/license_release_gallery.lic \
    vendor/oplus/camera/camera/proprietary/odm/etc/sensor/config/pakala_mtp_bmp5_0.json:$(TARGET_COPY_OUT_ODM)/etc/sensor/config/pakala_mtp_bmp5_0.json \
    vendor/oplus/camera/camera/proprietary/product/etc/camera/cdr_aging_set.json:$(TARGET_COPY_OUT_PRODUCT)/etc/camera/cdr_aging_set.json \
    vendor/oplus/camera/camera/proprietary/product/etc/camera/engineer_camera_config.json:$(TARGET_COPY_OUT_PRODUCT)/etc/camera/engineer_camera_config.json \
    vendor/oplus/camera/camera/proprietary/system/etc/permissions/privapp-permissions-oplus.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/privapp-permissions-oplus.xml \
    vendor/oplus/camera/camera/proprietary/system_ext/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/oplus_camera_default_grant_permissions_list.xml \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_bu52053nvx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_ccd_base.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_ccd_base.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_dynamic_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_dynamic_sensors_template.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_fcal_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_fcal_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_hdk_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_hdk_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_hdk_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_hdk_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_irq.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_lps22df_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_mtp_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_mtp_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_mtp_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_mtp_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_mtp_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_mtp_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_power_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_qrd_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_qrd_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_qrd_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_qrd_icm4x6xx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_qrd_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_qrd_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_qrd_tmd3765_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_qrd_tmd3765_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_sht4x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_sx932x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_tmd3765_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_tmd3765_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_vertigo_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_vertigo_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_vertigo_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_vertigo_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/bonito_vertigo_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bonito_vertigo_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/chre_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/chre_dynamic_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_bu52053nvx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_ccd_base.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_ccd_base.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_dynamic_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_dynamic_sensors_template.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_fcal_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_fcal_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_hdk_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_hdk_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_hdk_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_hdk_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_irq.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_lps22df_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_mtp_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_mtp_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_mtp_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_mtp_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_mtp_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_mtp_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_power_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_qrd_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qrd_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_qrd_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qrd_icm4x6xx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_qrd_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qrd_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_qrd_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_qrd_tmd2755_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_sht4x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_sx932x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_tmd2755_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_tmd2755_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_vertigo_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_vertigo_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_vertigo_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_vertigo_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/eliza_vertigo_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/eliza_vertigo_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_bu52053nvx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_ccd_base.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_ccd_base.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_dynamic_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_dynamic_sensors_template.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_dynamic_sensors_template.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_fcal_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_fcal_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_hdk_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_hdk_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_hdk_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_hdk_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_irq.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_lps22df_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_lps22df_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_mtp_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_mtp_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_mtp_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_mtp_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_mtp_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_mtp_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_mtp_oplus_camera_aon.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_mtp_oplus_camera_aon.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_power_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_qrd_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_qrd_default_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_qrd_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_qrd_icm4x6xx_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_qrd_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_qrd_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_qrd_tmd3765_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_qrd_tmd3765_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_sht4x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_sht4x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_sx932x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_sx932x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_tmd3765_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_tmd3765_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_vertigo_lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_vertigo_lsm6dso_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_vertigo_lsm6dso_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_vertigo_lsm6dso_1.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/pakala_vertigo_mmc56x3x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pakala_vertigo_mmc56x3x_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_common_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_common_sm8735.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_hummerFront_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_hummerFront_3.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_ktmFront_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ktmFront_2.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_ov32c4c_4_sm8735.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_paganiFront_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_paganiFront_3.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_paganiInFront_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_paganiInFront_3.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_petrelfrontmain_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_petrelfrontmain_3.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_petrelfrontsub_4.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_petrelfrontsub_4.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/qsh_camera_zffront_3.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/qsh_camera_zffront_3.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_amd.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v1_0_ttw.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v1_0_ttw.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v2_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_0_walk.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v3_0_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_0_walk.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v4_0_te_cd_regs.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_0_te_cd_regs.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v5_1_te_cd_regs.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0_sensors.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v6_0_te_cd_regs.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_direct_channel.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_direct_channel.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_flight_md.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_flight_md.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_offbody_detect_phone.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_offbody_detect_phone.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_psd_disable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_disable.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_psd_enable.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_psd_enable.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_transport_ppe.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_transport_ppe.json \
    vendor/oplus/camera/camera/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n00.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n00.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n01.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n01.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n02.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n02.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n03.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n03.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n04.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n04.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n05.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n05.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n06.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n06.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n07.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n07.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n08.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n08.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n09.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n09.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n10.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n10.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n11.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n11.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n12.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n12.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n13.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n13.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n14.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n14.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n15.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n15.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n28.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n28.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n29.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n29.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n30.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n30.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n31.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n31.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n32.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n32.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n33.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n33.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n34.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n34.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n37.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n37.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n40.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n40.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n41.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n41.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n42.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n42.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n43.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n43.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n44.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n44.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n45.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n45.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n46.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n46.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n49.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n49.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n50.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n50.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n51.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n51.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n52.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n52.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n53.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n53.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n54.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n54.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n55.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n55.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n56.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n56.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n57.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n57.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n58.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n58.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n63.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n63.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n64.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n64.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n65.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n65.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n66.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n66.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n67.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n67.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n68.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n68.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n69.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n69.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n70.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n70.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n71.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n71.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n72.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n72.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n73.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n73.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n74.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n74.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n75.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n75.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n76.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n76.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n77.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n77.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n78.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n78.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n79.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n79.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n80.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n80.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n81.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n81.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n82.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n82.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n83.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n83.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n84.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n84.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n85.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n85.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n86.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n86.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n87.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n87.bin \
    vendor/oplus/camera/camera/proprietary/vendor/lib64/bm5a79v08s13n88.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/bm5a79v08s13n88.bin

PRODUCT_PACKAGES += \
    vendor.oplus.hardware.cameraextension-V1-ndk \
    vendor.oplus.hardware.cameraextension@1.0 \
    libpenguin \
    vendor.oplus.hardware.cammidasservice@1.0 \
    libAPSClient-alog-jni \
    libAPSClient-cmd-jni-extension.oplus \
    libAPSClient-cmd-jni \
    libAPSClient-jni \
    libAncFilter_jni \
    libAncHumBokeh-jni \
    libAncHumanDoubleExposure-jni \
    libAncHumanRetain-jni_v2 \
    libAncHumanSegFigureFusion-jni \
    libAncHumanVideo-jni \
    libApsFaceBeautyPreviewProductJni \
    libApsSuperEISPreviewJni \
    libAvatarEngineRender \
    libAvatarEngineRenderNative \
    libCombineLut \
    libCombineLutJni \
    libFileExtender-jni \
    libHeifEncoderWrapper \
    libMsEffectSdk \
    libNativeWinBuffExchange \
    libOplusBlurPreviewJNI \
    libOplusStringJNI-extension.oplus \
    libOplusStringJNI \
    libSuperTextWrapper_system_ext \
    libXDocProcessSDK-jni \
    libXDocProcessSDK_system_ext \
    libYTCommon_system_ext \
    libapssuspend-jni.oplus \
    libarcsoft_wideselfie \
    libbinauralrenderer_wrapper.qti \
    libbsproxy \
    libextendfile_system_ext \
    libhoaeffects.qti \
    libhoaeffects_csim \
    libjni_wideselfie \
    libjnisingleblur_api \
    libjnistblur_api \
    liblivephoto.frc.jni \
    libmpbase_system_ext \
    liboplus-uah-client_system_ext \
    liboplusheifwriter \
    liboplushwui_jni \
    libortc_so.oplus \
    libsatellite_audio_jni.oplus \
    libsingle_camera_bokeh2_native \
    libsingle_camera_bokeh_native \
    libsoundtouch.oplus \
    libsoundtouch_jni.oplus \
    libst_mobile \
    libst_sticker_jni \
    libsuperNight.oplus \
    libvr_amb_engine \
    vendor.oplus.hardware.cameraMDM@1.0 \
    libOplusSecurity \
    libfusioninterpolation.arcsoft \
    ExtensionsService \
    OplusAppPlatform \
    OplusCamera \
    com.oplus.camera.unit.sdk.adapter \
    com.oplus.camera.unit.sdk
